# Generated by Django 5.1.3 on 2024-11-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('dni', models.CharField(max_length=15, verbose_name='DNI o Cedula')),
                ('email', models.EmailField(max_length=155, verbose_name='Correo Electronico')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Foto del Cliente')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customer',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_date', models.DateField(verbose_name='Vigencia')),
                ('term_days', models.PositiveIntegerField(verbose_name='Plazo (días)')),
                ('expiration_date', models.DateField(verbose_name='Vencimiento')),
                ('policy_type', models.CharField(max_length=100, verbose_name='Tipo de Póliza')),
                ('insured_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Asegurado')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa (%)')),
                ('minimum_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prima Mínima')),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prima')),
                ('extra_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cargo Adicional')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Derecho')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IVA (%)')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotizador de Seguro',
                'verbose_name_plural': 'Cotizador de Seguro',
                'db_table': 'insurance_policy',
                'ordering': ['-id'],
            },
        ),
    ]
