# Generated by Django 5.1.3 on 2024-11-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cotizador',
            table='Cotizador',
        ),
    ]
